#!/bin/bash
capacity=""
charging=""

if [ -d /sys/class/power_supply/BAT0 ]; then
    capacity=$(cat /sys/class/power_supply/BAT0/capacity)
    charging=$(cat /sys/class/power_supply/BAT0/status)
fi

capacity=${capacity:-0}
charging=${charging:-"Unknown"}

echo "{\"percentage\": $capacity, \"charging\": \"$charging\"}"
