#!/bin/bash

LC_TIME=ja_JP.UTF-8 date "+%m月 %d日 %A" | awk '
{
  gsub(/ /,"");        
  print substr($0,1,2);
  print substr($0,3,1);
  printf "\n";
  print substr($0,4,2);
  print substr($0,6,1);
  printf "\n";
  len = length($0);
  for(i=7; i<=len; i++) {
    print substr($0,i,1);
  }
}
'
