#!/bin/bash
vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n 1 | tr -d '%')
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
echo "{\"volume\": \"$vol\", \"muted\": \"$mute\"}"
    
pactl subscribe | grep --line-buffered "sink" |
while read _; do
    vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n 1 | tr -d '%')
    mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
    echo "{\"volume\": $vol, \"muted\": \"$mute\"}"
done
