#!/bin/sh
cd ~
setxkbmap -layout us -variant colemak

export _JAVA_AWT_WM_NONREPARENTING=1
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export GLFW_IM_MODULE=ibus
fcitx5 &

export XCURSOR_SIZE=24

exec Hyprland
