#!/bin/sh

# Creating the thumbnail images
msg_tag="ncmpcpp_event"
music_dir="$HOME/Music"
previewdir="$XDG_CONFIG_HOME/ncmpcpp/previews"
filename="$(mpc --format "$music_dir"/%file% current)"
albumbase64="$(mpc --format %album% current | base64)"
cleanalbumname="${albumbase64//\//_}"
previewname="$previewdir/$cleanalbumname.png"

[ -e "$previewname" ] || ffmpeg -y -i "$filename" -an -vf scale=480:480 "$previewname" > /dev/null 2>&1

# Sending the notification
dunstify -a "$(mpc --format "%artist%" current)" "$(mpc --format '\n%title%' current)" -h string:x-dunst-stack-tag:$msg_tag -i $previewname

# Displaying album art in ncmpcpp
if kitten icat --detect-support &>/dev/null; then
  kitten icat --clear

  window_size=$(stty size)
  window_height=$(echo $window_size | cut -d' ' -f1)
  window_width=$(echo $window_size | cut -d' ' -f2)
  spacing_from_edge=1

  image_size=40

  x_pos=$((spacing_from_edge))
  y_pos=$((window_height - (image_size / 2)))

  kitten icat --align center --scale-up --place ${image_size}x${image_size/2}@${x_pos}x${y_pos} $previewname
fi
