#!/usr/bin/env bash

if [[ $COLUMNS -gt 100 ]]; then
    rmpc remote --pid "$PID" set theme ~/.config/rmpc/themes/theme.ron
    rmpc remote --pid "$PID" status "Big theme set"
else
    rmpc remote --pid "$PID" set theme ~/.config/rmpc/themes/small.ron
    rmpc remote --pid "$PID" status "Small theme set"
fi
