set -g mouse on
set-option -g allow-rename off

set-option -g default-terminal 'screen-256color'
set-option -a terminal-features ',screen-256color:RGB'
set -g allow-passthrough on
set -as terminal-overrides ',screen-256color*:Ss=\E[%p1%d q:Se=\E[2 q'

# Start index at 1 for ergonomic reasons
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Lazygit
bind g new-window -n 'lazygit' lazygit

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"

# Better Session Kill Keybind
bind-key X confirm-before -p "Kill session? (y/n)" kill-session

# Theme Things
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

set -g pane-border-style 'fg=colour8'
set -g pane-active-border-style 'fg=colour15'

## Status Bar
set -g status-position top
set -g status-justify left
set -g status-style 'fg=colour15'
set -g status-left ''
set -g status-right ''

setw -g window-status-current-style 'fg=colour10 bg=default bold'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=colour10 dim'
setw -g window-status-bell-style 'fg=colour2 bg=default bold'

setw -g message-style 'fg=colour2 bg=default bold'
