#!/bin/sh

# --- ENVIRONMENT CONFIGURATION ---
# Set keyboard layout
riverctl keyboard-layout -variant colemak us

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Set input stuff
riverctl input pointer-1739-52560-SYNA3297:00_06CB:CD50_Touchpad tap enabled
riverctl input pointer-1739-52560-SYNA3297:00_06CB:CD50_Touchpad tap-button-map left-right-middle
riverctl input pointer-1739-52560-SYNA3297:00_06CB:CD50_Touchpad natural-scroll enabled
riverctl input pointer-1739-52560-SYNA3297:00_06CB:CD50_Touchpad scroll-factor 0.75

riverctl default-attach-mode bottom

# --- VISUAL CONFIGURATIONS ---
# Set background and border color
riverctl background-color 0x222222
riverctl border-color-focused 0xbbbbbb
riverctl border-color-unfocused 0x444444
riverctl border-color-urgent 0x444444

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Make various apps use Server Side Decorations
riverctl rule-add -app-id "zen-alpha" ssd
riverctl rule-add -app-id "thunar" ssd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 5 -outer-padding 5 -main-ratio 0.55 &

# --- MAPPINGS ---
riverctl map normal Super Return spawn kitty
riverctl map normal Super Space spawn "tofi-drun --drun-launch=true"
riverctl map normal Super+Shift S spawn 'grim -g "$(slurp -d)" - | wl-copy'

riverctl map normal Super W close
riverctl map normal Super+Shift Q exit

riverctl map normal Super N focus-view next
riverctl map normal Super E focus-view previous

riverctl map normal Super+Shift N swap next
riverctl map normal Super+Shift E swap previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
# riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.01"
riverctl map normal Super I send-layout-cmd rivertile "main-ratio +0.01"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift I send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt N move down 100
riverctl map normal Super+Alt E move up 100
riverctl map normal Super+Alt I move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control N snap down
riverctl map normal Super+Alt+Control E snap up
riverctl map normal Super+Alt+Control I snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift N resize vertical 100
riverctl map normal Super+Alt+Shift E resize vertical -100
riverctl map normal Super+Alt+Shift I resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+P to toggle float
riverctl map normal Super P toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# # Declare a passthrough mode. This mode has only a single mapping to return to
# # normal mode. This makes it useful for testing a nested wayland compositor
# riverctl declare-mode passthrough
#
# # Super+F11 to enter passthrough mode
# riverctl map normal Super F11 enter-mode passthrough
#
# # Super+F11 to return to normal mode
# riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
    
    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn '$HOME/shell_scripts/change_brightness_w inc'
    riverctl map $mode None XF86MonBrightnessDown spawn '$HOME/shell_scripts/change_brightness_w dec'
done

# --- AUTO-STARTS ---
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "wlr-randr --output eDP-1 --scale 1.5"
riverctl spawn $HOME/.config/river/background.sh
riverctl spawn $HOME/.config/eww/launch_bar
riverctl spawn dunst
riverctl spawn fcitx5
