font=mononoki Nerd Font Mono:size=13
pad=4x4x4x4

[bell]
system=no

[cursor]
blink=yes

[colors-dark]
# alpha=1.0
# alpha-mode=default
background=191919
foreground=c5c8c6

regular0=2b303b
regular1=bf616a
regular2=a3be8c
regular3=ebcb8b
regular4=8fa1b3
regular5=b48ead
regular6=96b5b4
regular7=c0c5ce

bright0=65737e
bright1=bf616a
bright2=a3be8c
bright3=ebcb8b
bright4=8fa1b3
bright5=b48ead
bright6=96b5b4
bright7=eff1f5
