# GENERAL
general {
    no_fade_in = true
    grace = 0
    disable_loading_bar = true
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 22
  font_family = mononoki Nerd Font
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-H:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 95
  font_family = mononoki Nerd Font
  position = 0, 200
  halign = center
  valign = center
}

label {
    monitor =
    size = 250, 60
    position = 0, -100
    text = <i><span>[currently locked]</span></i>
    color = rgba(242, 243, 244, 0.75)
    font_size = 24
    font_family = mononoki Nerd Font
    halign = center
    valign = center
}

label {
    monitor =
    halign = left
    valign = bottom
    size = 250, 60
    position = 50, 50
    font_size = 24
    font_family = mononoki Nerd Font
    color = rgba(242, 243, 244, 0.75)
    text = cmd[] echo "$(lswt | awk 'NR>1 {print $2}')"
}

label {
    montior =
    halign = center
    valign = bottom
    size = 250, 60
    position = 0, 50
    font_size = 24
    font_family = mononoki Nerd Font
    text_align = center
    color = rgba(242, 243, 244, 0.75)
    text = cmd[update:1000] echo "$(mpc -f '[now listening to: %artist% - %title%[ (on %album%)]]' current) $(mpc status '[\n%currenttime% / %totaltime% (%percenttime%)]')"
}

label {
    monitor =
    halign = right
    valign = bottom
    size = 250, 60
    position = -50, 50
    font_size = 24
    font_family = mononoki Nerd Font
    color = rgba(242, 243, 244, 0.75)
    text = cmd[] echo "logged in as: $(whoami)"
}
